name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install SDL2
      run: sudo apt-get install -y libsdl2-dev
    - name: install SDL2_ttf
      run: sudo apt-get install -y libsdl2-ttf-dev
    - name: install GLM
      run: sudo apt-get install -y libglm-dev
    - name: configure
      run: cmake CMakeLists.txt
    - name: build
      run: make
